### ISSUE TITLE
ur code sucks

### ISSUE THREAD

**Issue by Nero-X** [The-SourceCode/Discord.js-Bot-Development#1]
ur code is great

**Comment by Jacxk** [comment]
I agree man, it's great

**Comment by donkeymonkey1** [comment]
:closethisshit:

**Comment by Nero-X** [comment]
no u

**Comment by XenonLaggyzYT** [comment]
i fucked up when i was writing it so i used the code on here for the warning system and it also was invalid so im double fucked

**Comment by PantheraRed** [comment]
It doesn't matter if code is great or not, it matters if you really wanna learn and stop being dependent on it, i was watching the whole tutorial and didn't copied a thing from here, i followed the whole tutorial and learned every element, now i can code a simple send message command just like that, i personally came here because after 1 month i realised a prefix glitch which can be found in issues named as "prefix problem", overall this code is perfect for learning :+1:

**Comment by Nero-X** [comment]
no u
